export const fallbackProjects = [
  {
    id: 1,
    slug: "real-time-object-detection",
    title: "Real-Time Object Detection",
    short_description: "YOLOv8 running 100% in the browser via ONNX Runtime Web -- live webcam, image upload, demo gallery with sci-fi bounding boxes.",
    full_description: "Built a real-time object detection system running entirely in the browser using YOLOv8 and ONNX Runtime Web. Features include live webcam detection, image upload, and a demo gallery with futuristic bounding box overlays. Zero server, complete privacy.",
    category: "Computer Vision",
    tech_stack: ["React", "TypeScript", "ONNX Runtime", "YOLOv8", "Canvas API", "Vite"],
    thumbnail_url: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=640&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=1200&q=80",
    demo_url: "https://real-time-object-detection-three.vercel.app",
    repo_url: "https://github.com/Dantezp96/real-time-object-detection",
    metrics: null,
  },
  {
    id: 2,
    slug: "satellite-image-segmentation",
    title: "Satellite Image Segmentation",
    short_description: "FLAIR U-Net+ResNet34 trained on real aerial imagery, running in the browser via ONNX Runtime Web -- interactive satellite map with 15-class land cover segmentation.",
    full_description: "Interactive satellite image segmentation platform using FLAIR U-Net+ResNet34. Click anywhere on a satellite map to segment land cover into 15 classes (buildings, vegetation, water, roads, etc.). Model runs 100% in-browser via ONNX Runtime Web with MapLibre GL for smooth map interaction.",
    category: "Image Analysis",
    tech_stack: ["React", "TypeScript", "ONNX Runtime", "PyTorch", "MapLibre GL", "Vite"],
    thumbnail_url: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=640&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&q=80",
    demo_url: "https://satellite-image-segmentation.vercel.app",
    repo_url: "https://github.com/Dantezp96/satellite-image-segmentation",
    metrics: null,
  },
  {
    id: 3,
    slug: "nlp-sentiment-dashboard",
    title: "NLP Sentiment Dashboard",
    short_description: "Real-time sentiment analysis with RoBERTa — interactive dashboard with word clouds, trends, and batch processing.",
    full_description: "Sentiment analysis dashboard powered by RoBERTa (HuggingFace Transformers). Analyze text in real-time with confidence scores, batch process CSV files, and visualize trends with interactive word clouds and charts. Built with Gradio for a clean UI.",
    category: "NLP",
    tech_stack: ["Python", "HuggingFace", "Gradio", "Transformers", "PyTorch", "Matplotlib"],
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=640&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    demo_url: "https://nlp-sentiment-dashboard-production.up.railway.app",
    repo_url: "https://github.com/Dantezp96/nlp-sentiment-dashboard",
    metrics: null,
  },
  {
    id: 4,
    slug: "data-pipeline-etl",
    title: "RIPS ETL Pipeline",
    short_description: "High-performance ETL pipeline processing +1M RIPS healthcare files daily with Apache Airflow, Polars Lazy API, and SHA-256 deduplication — 40% faster ingestion.",
    full_description: "Production ETL pipeline processing +1M RIPS healthcare files daily with Apache Airflow (Dynamic Task Mapping, ThreadPoolExecutor). Reduced ingestion times 40% migrating from Pandas to Polars Lazy API. 3-layer validation pipeline (structure, content, relation) with SHA-256 deduplication and MinSalud/SISPRO integration, achieving 99.9% data integrity. Optimized SQL Server queries with in-process cache (27-74x speedup) and Celery with 3 specialized workers.",
    category: "Data Engineering",
    tech_stack: ["Python", "Apache Airflow", "Polars", "Celery", "Azure", "PostgreSQL"],
    thumbnail_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=640&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80",
    demo_url: null,
    repo_url: null,
    metrics: '{"Files/Day": "1M+", "Integrity": "99.9%", "Speedup": "27-74x", "Rules": "11.4K+"}',
  },
  {
    id: 5,
    slug: "medical-image-classification",
    title: "Medical Image Classification",
    short_description: "Multi-modal AI medical diagnosis: chest X-ray (18 pathologies + GradCAM), skin cancer (7 types), brain tumor (4 classes), and breast cancer detection — 100% in-browser.",
    full_description: "Multi-modal medical image classification platform with 4 AI models running entirely in the browser. Chest X-Ray mode uses DenseNet121 trained on 400K+ images detecting 18 pulmonary conditions with GradCAM heatmaps. Skin Cancer mode uses MobileNetV2 on HAM10000 classifying 7 lesion types including Melanoma. Brain Tumor mode uses Swin Transformer on brain MRIs detecting Glioma, Meningioma, and Pituitary tumors. Breast Cancer mode uses MobileNetV2 trained on PatchCamelyon (327K histopathology patches) for binary metastatic tissue detection. All inference via ONNX Runtime Web WASM — zero server, complete privacy.",
    category: "Computer Vision",
    tech_stack: ["React", "TypeScript", "ONNX Runtime Web", "DenseNet121", "MobileNetV2", "Swin Transformer", "GradCAM", "Vite"],
    thumbnail_url: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=640&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1200&q=80",
    demo_url: "https://medical-image-classification-gilt.vercel.app",
    repo_url: "https://github.com/Dantezp96/medical-image-classification",
    metrics: '{"Models": "4", "Classes": "31 total", "Inference": "<1.5s", "Privacy": "100% Browser"}',
  },
  {
    id: 6,
    slug: "time-series-forecasting",
    title: "Energy Demand Forecasting",
    short_description: "Multi-model forecasting dashboard comparing Prophet, Fourier Series, Seasonal Naive and Weekly Average on PJM energy data — best MAPE 4.47%.",
    full_description: "Interactive energy demand forecasting dashboard comparing 4 prediction models: Facebook Prophet, Fourier Series regression, Seasonal Naive, and Weekly Average. Features bilingual ES/EN interface, historical data with aggregation controls, 1-7 day forecasting with model selection, and a multi-model comparison chart with metrics table. React + Recharts frontend, FastAPI backend.",
    category: "ML / Time Series",
    tech_stack: ["Python", "FastAPI", "Prophet", "NumPy", "React", "Recharts", "Pandas"],
    thumbnail_url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=640&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&q=80",
    demo_url: "https://energy-forecast-xi.vercel.app",
    repo_url: "https://github.com/Dantezp96/energy-demand-forecasting",
    metrics: '{"Models": "4", "Best MAPE": "4.47%", "Forecast": "1-7 days"}',
  },
];
